on:
  push:
  pull_request:
  workflow_dispatch:

name: CI
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: go fmt ./...
    - name: Build
      run: go build ./...
    - name: Vet
      run: go vet ./...
    - name: Secure
      run: make secure
